#!/bin/sh
#
# mkdep,v 1.3 1996/04/10 15:41:58 tardieu Exp
#

TOP_SRCDIR=`cd $1 && pwd`
shift

SRCDIR=`cd $1 && pwd`
shift

INCLUDE_DIRS="${SRCDIR} "

export LC_COLLATE=C

while [ $# -ne 0 ]; do
  case "$1" in
    -I*)
      INCLUDE_DIRS="${INCLUDE_DIRS} "`cd ${1#-I} && pwd`
      shift
      ;;
    *)
      shift
      ;;
  esac
done

FNAME=${SRCDIR}/Makefile.am
MKDEP="### DO NOT REMOVE THIS LINE, IT IS USED BY MAKEDEPEND ###"
rm -f $FNAME.bak
cp $FNAME $FNAME.bak
(sed -e "/$MKDEP/,\$d" < $FNAME.bak
echo $MKDEP
for alifile in *.ali; do
  echo "Processing ${alifile}..." > /dev/stderr
  withlist=
  while read key unitfile rest; do
    case ${key} in
      D)
        for dir in ${INCLUDE_DIRS}; do
          if [ -f ${dir}/${unitfile} ]; then
            withlist="${withlist} ${dir}/${unitfile}"
          fi
        done
        ;;
      *)
        ;;
    esac
  done < ${alifile}
  withlist=`echo "${withlist}" | tr ' ' '\n' | sort`
  echo -n "${alifile%.ali}.lo:"
  for depfile in ${withlist}; do
    if [ "${depfile#${SRCDIR}}" != "${depfile}" ]; then
      echo " \\"
      echo -ne "\t${depfile/${SRCDIR}/\$(srcdir)}"
    elif [ "${depfile#${TOP_SRCDIR}}" != "${depfile}" ]; then
      echo " \\"
      echo -ne "\t${depfile/${TOP_SRCDIR}/\$(top_srcdir)}"
    fi
  done
  echo
done
) > $FNAME
