#! /bin/sh

echo "Libtoolizing"
libtool_m4=`libtoolize --force | sed -n -e '/You should add the contents of \`\([^'\'']*\)'\''.*$/s//\1/p'`
if [ -n "$libtool_m4" ]; then
  ln -sf $libtool_m4 support/libtool.m4
fi

echo "Running aclocal"
aclocal -I support --output=support/aclocal.m4

echo "Running autoconf"
autoconf -I support

echo "Running automake"
ln -sf support/aclocal.m4
automake --add-missing --foreign
