#!/bin/sh
ARCHIVEDATE="-`date +%Y%m%d`"
ARHIVEVERSION=0.3w
ARCHIVE=../xmada-$ARHIVEVERSION$ARCHIVEDATE.tar
TMP=xmada-$ARHIVEVERSION$ARCHIVEDATE

./support/reconfig

rm -rf $TMP
mkdir $TMP
(tar cf - -T MANIFEST) | (cd $TMP && tar xf -)

(cd $TMP && \
 for f in `find -type l | grep -v aclocal.m4`; do \
   rm -f $f; 
   cp -p ../$f $f; \
 done)

tar cf $ARCHIVE $TMP
gzip -9f $ARCHIVE

(cd $TMP && ./configure && make) && rm -rf $TMP
